//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB_PLATFORM007.WCF_PLATFORM001 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF_PLATFORM001.EEQMU_MODEL")]
    public interface EEQMU_MODEL {
        
        // CODEGEN: Generating message contract since the operation SUBMIT_ACTION() is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EEQMU_MODEL/SUBMIT_ACTION()", ReplyAction="http://tempuri.org/EEQMU_MODEL/SUBMIT_ACTION()Response")]
        WEB_PLATFORM007.WCF_PLATFORM001.SUBMIT_ACTIONResponse SUBMIT_ACTION(WEB_PLATFORM007.WCF_PLATFORM001.SUBMIT_ACTIONRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SUBMIT_ACTIONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.datacontract.org/2004/07/PLATFORM700TOREVO", Order=0)]
        public PLATFORM700TOREVO.WF_ACTION_OBJECT WF_ACTION_OBJECT;
        
        public SUBMIT_ACTIONRequest() {
        }
        
        public SUBMIT_ACTIONRequest(PLATFORM700TOREVO.WF_ACTION_OBJECT WF_ACTION_OBJECT) {
            this.WF_ACTION_OBJECT = WF_ACTION_OBJECT;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SUBMIT_ACTIONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://schemas.datacontract.org/2004/07/PLATFORM700TOREVO", Order=0)]
        public PLATFORM700TOREVO.WF_ACTION_MESSAGE WF_ACTION_MESSAGE;
        
        public SUBMIT_ACTIONResponse() {
        }
        
        public SUBMIT_ACTIONResponse(PLATFORM700TOREVO.WF_ACTION_MESSAGE WF_ACTION_MESSAGE) {
            this.WF_ACTION_MESSAGE = WF_ACTION_MESSAGE;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EEQMU_MODELChannel : WEB_PLATFORM007.WCF_PLATFORM001.EEQMU_MODEL, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EEQMU_MODELClient : System.ServiceModel.ClientBase<WEB_PLATFORM007.WCF_PLATFORM001.EEQMU_MODEL>, WEB_PLATFORM007.WCF_PLATFORM001.EEQMU_MODEL {
        
        public EEQMU_MODELClient() {
        }
        
        public EEQMU_MODELClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EEQMU_MODELClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EEQMU_MODELClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EEQMU_MODELClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WEB_PLATFORM007.WCF_PLATFORM001.SUBMIT_ACTIONResponse WEB_PLATFORM007.WCF_PLATFORM001.EEQMU_MODEL.SUBMIT_ACTION(WEB_PLATFORM007.WCF_PLATFORM001.SUBMIT_ACTIONRequest request) {
            return base.Channel.SUBMIT_ACTION(request);
        }
        
        public PLATFORM700TOREVO.WF_ACTION_MESSAGE SUBMIT_ACTION(PLATFORM700TOREVO.WF_ACTION_OBJECT WF_ACTION_OBJECT) {
            WEB_PLATFORM007.WCF_PLATFORM001.SUBMIT_ACTIONRequest inValue = new WEB_PLATFORM007.WCF_PLATFORM001.SUBMIT_ACTIONRequest();
            inValue.WF_ACTION_OBJECT = WF_ACTION_OBJECT;
            WEB_PLATFORM007.WCF_PLATFORM001.SUBMIT_ACTIONResponse retVal = ((WEB_PLATFORM007.WCF_PLATFORM001.EEQMU_MODEL)(this)).SUBMIT_ACTION(inValue);
            return retVal.WF_ACTION_MESSAGE;
        }
    }
}
